= Feed API
user-api-docs
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:

[[resources-comment]]
== Comment

[[resources-feed-comment-getComment]]
=== Comment 댓글 조회

operation::feed/comment/getComment[snippets='http-request,path-parameters,http-response,response-fields']

[[resources-feed-comment-createComment]]
=== Comment 댓글 생성

operation::feed/comment/createComment[snippets='http-request,path-parameters,request-fields,http-response']

[[resources-feed-comment-updateComment]]
=== Comment 댓글 수정

operation::feed/comment/updateComment[snippets='http-request,path-parameters,request-fields,http-response']

[[resources-feed-comment-deleteComment]]
=== Comment 댓글 삭제

operation::feed/comment/deleteComment[snippets='http-request,path-parameters,http-response']

[[resources-like]]
== Like

[[resources-feed-like-getLike]]
=== Like 좋아요 조회

operation::feed/like/getLike[snippets='http-request,http-response,response-fields']

[[resources-feed-like-createLike]]
=== Like 좋아요 추가

operation::feed/like/createLike[snippets='http-request,path-parameters,http-response']


[[resources-feed-like-deleteLike]]
=== Like 좋아요 취소

operation::feed/like/deleteLike[snippets='http-request,path-parameters,http-response']
